# Generated by Django 2.2.16 on 2022-10-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221013_1351'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='uniq_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='you_cant_refollow'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'user'), name='you_cant_on_yourself_user'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('author', 'author'), name='You_cant_on_yourself_author'),
        ),
    ]
