# Generated by Django 2.2.16 on 2022-10-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20221013_1430'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='you_cant_refollow',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='you_cant_on_yourself',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_follower'),
        ),
    ]
